version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq-1
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  kafka-net:
    driver: bridge

volumes:
  kafka_data:
